apiVersion: v1
kind: Service
metadata:
  name: merchant-web
  labels:
    app: merchant-web
spec:
  type: NodePort
  ports:
  - port: 80
    name: merchant-web
  selector:
    app: merchant-web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: merchant-web
  name: merchant-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: merchant-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: merchant-web
    spec:
      imagePullSecrets: 
      - name: lm-registry-auth
      containers:
      - name: merchant-web
        imagePullPolicy: IfNotPresent
        image: IMAGE_NAME
        volumeMounts:
          - name: tz-config
            mountPath: /usr/share/zoneinfo/Asia/Shanghai
          - name: tz-config
            mountPath: /etc/localtime
          - name: timezone
            mountPath: /etc/timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: "File"
        name: tz-config
      - hostPath:
          path: /etc/timezone
          type: "File"
        name: timezone
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
